name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest  # 必须用 macOS 环境

    steps:
      - uses: actions/checkout@v4  # 拉取代码

      - name: Install CocoaPods (if needed)
        run: |
          sudo gem install cocoapods
          pod install

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -workspace YourProject.xcworkspace \
            -scheme YourScheme \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Archive Artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: XcodeBuildOutput
          path: build/
